const members = [
  {
    "name": "Jane ",
    "age_pronouns": "22 (she/her)",
    "performance_roles": "Hanayo/hanamaru/Emma/ren/kozue  ",
    "BTS_role": "Costume lead, photo team ",
    "insta": "@Missdottyjane",
    "attribute": "Pure Attribute",
    "height": "173cm",
    "fav_food": "Bread",
    "disliked_food": "Eggs",
    "charm": "Helpful ",
    "photo_path": "imgs/member_imgs/dotty_jane.jpg",
    "cropped_path": "imgs/member_imgs/dotty_jane_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Lala !!",
    "age_pronouns": "23 (she/they/him)",
    "performance_roles": "Nozomi, Mari, Kanata, Chisato, Kaho",
    "BTS_role": "Secretary, Dance Lead, Costume , Character",
    "insta": "@seafoamsailor",
    "attribute": "Pure Attribute",
    "height": "152cm",
    "fav_food": "Pancakes!",
    "disliked_food": "Anything with too much flavor or spice!",
    "charm": "My drive to help and support everyone!",
    "photo_path": "imgs/member_imgs/lala.jpg",
    "cropped_path": "imgs/member_imgs/lala_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "ed",
    "age_pronouns": "23 (he/him)",
    "performance_roles": "3rd understudy twice removed",
    "BTS_role": "IT guy, costume, tech",
    "insta": "@gaycultists",
    "attribute": "Cool Attribute",
    "height": "162cm",
    "fav_food": "samosas",
    "disliked_food": "jello",
    "charm": "im good at picking up new crafts",
    "photo_path": "imgs/member_imgs/ed.jpg",
    "cropped_path": "imgs/member_imgs/ed_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "River",
    "age_pronouns": "20 (he/him)",
    "performance_roles": "Eli, Dia, Shiki, Megumi, Tsubasa",
    "BTS_role": "co Tech lead, Sales",
    "insta": "@punk.idol.river",
    "attribute": "Cool Attribute",
    "height": "167cm",
    "fav_food": "Cheeseburgers",
    "disliked_food": "Sour Cream",
    "charm": "Ultimate idol otaku & dedicated wota!",
    "photo_path": "imgs/member_imgs/river.png",
    "cropped_path": "imgs/member_imgs/river_cropped.png",
    "about": "Here is an introduction!"
  },
  {
    "name": "Kay",
    "age_pronouns": "27 (she/her)",
    "performance_roles": "Kotori, Ruby, Rina, Kinako, Sakaya",
    "BTS_role": "Graphic Team Lead,On teams: Promo, Character, Photo, Costume ",
    "insta": "@Kaykay_if_you_craycray",
    "attribute": "Pure Attribute",
    "height": "157cm",
    "fav_food": "Strawberries!",
    "disliked_food": "Tomatoes",
    "charm": "Always prepared!",
    "photo_path": "imgs/member_imgs/kay.jpg",
    "cropped_path": "imgs/member_imgs/kay_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "RJ",
    "age_pronouns": "22 (he/they)",
    "performance_roles": "Sumire/Shioriko/Understudy",
    "BTS_role": "Dance team",
    "insta": "@Idol.girl.trash",
    "attribute": "Smile Attribute",
    "height": "170cm",
    "fav_food": "French fries",
    "disliked_food": "Onions",
    "charm": "Triple Threat Singer/Dancer/Actor…sort of ",
    "photo_path": "imgs/member_imgs/rj.jpg",
    "cropped_path": "imgs/member_imgs/rj_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Sibyl",
    "age_pronouns": "28 (she/they/him)",
    "performance_roles": "Karin, Keke, Rurino, understudy ",
    "BTS_role": "Tech, photo",
    "insta": "@sibyl.iv",
    "attribute": "Cool Attribute",
    "height": "162cm",
    "fav_food": "Ice cream",
    "disliked_food": "Sweet food that isn’t a dessert ",
    "charm": "Divine favor ",
    "photo_path": "imgs/member_imgs/sibyl.jpg",
    "cropped_path": "imgs/member_imgs/sibyl_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Audrey",
    "age_pronouns": "21 (she/her)",
    "performance_roles": "Lanzhu Zhong,  Natsuki Onitsuka, understudy",
    "BTS_role": "costume team, dance team",
    "insta": "@ominouspug",
    "attribute": "Pure Attribute",
    "height": "149cm",
    "fav_food": "pasta <3",
    "disliked_food": "carrots",
    "charm": "short... im so short... i got cute round cheeks though!",
    "photo_path": "imgs/member_imgs/audrey.jpg",
    "cropped_path": "imgs/member_imgs/audrey_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Ivy Vinca",
    "age_pronouns": "34 (she/her)",
    "performance_roles": "Anju from Arise, main cast understudy",
    "BTS_role": "n/a",
    "insta": "@Ivyvinca",
    "attribute": "Cool Attribute",
    "height": "170cm",
    "fav_food": "White tuna sashimi",
    "disliked_food": "Beets and bell peppers",
    "charm": "Starry eyes and endless determination",
    "photo_path": "imgs/member_imgs/ivy_vinca.jpg",
    "cropped_path": "imgs/member_imgs/ivy_vinca_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Beppy",
    "age_pronouns": "21 (he/him)",
    "performance_roles": "Mia Taylor, Tomari Onitsuka, Main Cast Understudy!",
    "BTS_role": "costume team",
    "insta": "@Stwawbeppy",
    "attribute": "Cool Attribute",
    "height": "160cm!",
    "fav_food": "Coca Cola (if you specifically need a food, probably most meat!)",
    "disliked_food": "Most LOL",
    "charm": "My Adaptability / Ability to quickly learn new skills for the things I love!",
    "photo_path": "imgs/member_imgs/beppy.jpg",
    "cropped_path": "imgs/member_imgs/beppy_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Chris",
    "age_pronouns": "20 (he/they)",
    "performance_roles": "understudy",
    "BTS_role": "n/a",
    "insta": "@ghostofmontague",
    "attribute": "Cool Attribute",
    "height": "162cm",
    "fav_food": "Coffee ice cream",
    "disliked_food": "Spinach",
    "charm": "My perfectionism (both a positive and a negative lol)",
    "photo_path": "imgs/member_imgs/chris.jpg",
    "cropped_path": "imgs/member_imgs/chris_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Brittany ",
    "age_pronouns": "23 (she/her)",
    "performance_roles": "Wein, Erena, Mao",
    "BTS_role": "n/a",
    "insta": "@moonside_cosplay",
    "attribute": "Cool Attribute",
    "height": "155cm ",
    "fav_food": "Japanese Curry ",
    "disliked_food": "Artichoke hearts, beets ",
    "charm": "I never give up even if something seems impossible! ",
    "photo_path": "imgs/member_imgs/brittany.jpg",
    "cropped_path": "imgs/member_imgs/brittany_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Minnie",
    "age_pronouns": "21 (they/them)",
    "performance_roles": "Honoka/Chika/Ayumu",
    "BTS_role": "costume team",
    "insta": "@idoladora",
    "attribute": "Smile Attribute",
    "height": "175cm",
    "fav_food": "so many but my top would be panera grilled cheese",
    "disliked_food": "mashed potatoes",
    "charm": "my stage presence and my determination",
    "photo_path": "imgs/member_imgs/minnie.jpg",
    "cropped_path": "imgs/member_imgs/minnie_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "ashes",
    "age_pronouns": "30 (she/they)",
    "performance_roles": "n/a",
    "BTS_role": "graphics and promo",
    "insta": "@svedka.cos",
    "attribute": "Cool Attribute",
    "height": "179cm",
    "fav_food": "Buffalo wings",
    "disliked_food": "Avocado",
    "charm": "Very loud wotagei 🤭",
    "photo_path": "imgs/member_imgs/ashes.jpg",
    "cropped_path": "imgs/member_imgs/ashes.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Ruth",
    "age_pronouns": "23 (she/her)",
    "performance_roles": "n/a",
    "BTS_role": "co-tech lead",
    "insta": "@ach00_cos",
    "attribute": "Cool Attribute",
    "height": "170cm",
    "fav_food": "Dark chocolate",
    "disliked_food": "Pickles",
    "charm": "Just a chill girl ✌️",
    "photo_path": "imgs/member_imgs/ruth.jpg",
    "cropped_path": "imgs/member_imgs/ruth_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Claudia",
    "age_pronouns": "18 (she/they/him)",
    "performance_roles": "n/a",
    "BTS_role": "Graphics team + sales team",
    "insta": "@goldngazes",
    "attribute": "Cool Attribute",
    "height": "160cm",
    "fav_food": "Cheese pizza",
    "disliked_food": "beans of any kind",
    "charm": "my charisma and dedication !",
    "photo_path": "imgs/member_imgs/claudia.jpg",
    "cropped_path": "imgs/member_imgs/claudia_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Dana",
    "age_pronouns": "28 (she/her)",
    "performance_roles": "Nico/Yohane/Kasumi/Kanon",
    "BTS_role": "Costume team, character team lead",
    "insta": "@kizunadana",
    "attribute": "Smile Attribute",
    "height": "152cm",
    "fav_food": "Chocolate chip cookies",
    "disliked_food": "Seafood",
    "charm": "My positive attitude!",
    "photo_path": "imgs/member_imgs/dana.jpg",
    "cropped_path": "imgs/member_imgs/dana_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Aria",
    "age_pronouns": "22 (they/them)",
    "performance_roles": "understudy",
    "BTS_role": "n/a",
    "insta": "@damnariacosplays",
    "attribute": "Cool Attribute",
    "height": "170cm",
    "fav_food": "Kimchi",
    "disliked_food": "Sardines",
    "charm": "I’m a wig commissioner",
    "photo_path": "imgs/member_imgs/aria.jpg",
    "cropped_path": "imgs/member_imgs/aria_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Hime",
    "age_pronouns": "26 (she/they/him)",
    "performance_roles": "Understudy",
    "BTS_role": "tech team",
    "insta": "@Hexadecimal.png ",
    "attribute": "Smile Attribute",
    "height": "169cm",
    "fav_food": "Bibimbap",
    "disliked_food": "Mushrooms",
    "charm": "I’m spindly",
    "photo_path": "imgs/member_imgs/hime.jpg",
    "cropped_path": "imgs/member_imgs/hime_cropped.png",
    "about": "Here is an introduction!"
  },
  {
    "name": "Leo! ",
    "age_pronouns": "20 (he/they/star)",
    "performance_roles": "Yuuna and understudy!",
    "BTS_role": "n/a ",
    "insta": "@honkboyleo",
    "attribute": "Smile Attribute",
    "height": "171cm",
    "fav_food": "chocolate!",
    "disliked_food": "tomatoes >m<",
    "charm": "my enthusiasm! ",
    "photo_path": "imgs/member_imgs/leo.jpg",
    "cropped_path": "imgs/member_imgs/leo_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Miso",
    "age_pronouns": "25 (she/her)",
    "performance_roles": "Rin/You/Ai/Mei/ The other girl I can’t remember ",
    "BTS_role": "Promo lead, graphics team, costume team, sales team, tech team, photo team",
    "insta": "@badinfluencesenpai",
    "attribute": "Cool Attribute",
    "height": "162cm",
    "fav_food": "Ice cream and steak",
    "disliked_food": "Rosemary",
    "charm": "Loyal and honest friend to the end!",
    "photo_path": "imgs/member_imgs/miso.jpg",
    "cropped_path": "imgs/member_imgs/miso_cropped.jpg",
    "about": "Here is an introduction!"
  },
  {
    "name": "Jaden",
    "age_pronouns": "22 (he/him)",
    "performance_roles": "n/a",
    "BTS_role": "Tech",
    "insta": "@junky_jaden",
    "attribute": "Pure Attribute",
    "height": "170cm",
    "fav_food": "dumplings",
    "disliked_food": "raw tomato",
    "charm": "My tastes! The art, music, and media I enjoy are a unique facet of my personality.",
    "photo_path": "imgs/member_imgs/jaden.jpg",
    "cropped_path": "imgs/member_imgs/jaden_cropped.jpg",
    "about": "Here is an introduction!"
  }
]

export default members;
